version: 1

filters:
  onlyimportant:
    (): temos.tools.logging.LevelsFilter
    levels:
    - CRITICAL
    - ERROR
    - WARNING
  noimportant:
    (): temos.tools.logging.LevelsFilter
    levels:
    - INFO
    - DEBUG
    - NOTSET

formatters:
  verysimple:
    format: '%(message)s'
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    datefmt: '%d/%m/%y %H:%M:%S'

  colorlog:
    (): colorlog.ColoredFormatter
    format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s]
      - %(message)s'
    datefmt: '%d/%m/%y %H:%M:%S'

  log_colors:
    DEBUG: purple
    INFO: green
    WARNING: yellow
    ERROR: red
    CRITICAL: red

handlers:
  console:
    class: rich.logging.RichHandler # logging.StreamHandler
    formatter: verysimple # colorlog
    rich_tracebacks: true

  file_out:
    class: logging.FileHandler
    formatter: simple
    filename: logs.out
    filters:
    - noimportant

  file_err:
    class: logging.FileHandler
    formatter: simple
    filename: logs.err
    filters:
    - onlyimportant

root:
    level: ${logger_level}
    handlers:
    - console
    - file_out
    - file_err

disable_existing_loggers: false